
/* USER TYPES */
export const GET_FORMS = 'GET_FORMS';
export const PUBLISH_FORM = 'PUBLISH_FORM';
export const GET_PUBLISHED_FORMS = 'GET_PUBLISHED_FORMS';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const GET_FORMS_ERROR = 'GET_FORMS_ERROR';
/* FORM TYPES */
export const GET_FORM = "GET_FORM";
export const UPDATE_FORM = "UPDATE_FORM";
export const CREATE_FORM = "CREATE_FORM";
export const FORM_UPDATE_ERROR = "FORM_UPDATE_ERROR";